Repository cs361w2019-osu/sprint1-project-group-6, pull requests merged in 2019-02, with the labels that each got.

#27 Tutorial on hover
  src/main/java/assets/css/custom.css
  src/main/java/assets/images/ship-clipart-1.jpg
  src/main/java/views/ApplicationController/index.ftl.html
Labels: feature

#31 Add ship selection
  src/main/java/assets/css/custom.css
  src/main/java/views/ApplicationController/index.ftl.html
Labels: feature

#33 fixed invalid css and removed old ship placement buttons
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: bug

#34 fixed tooltip moving divs on hover
  src/main/java/assets/css/custom.css
Labels: bug

#36 display name->ship placement
  src/main/java/views/ApplicationController/index.ftl.html
Labels: feature

#37 display name is now reflected in scorecard
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: feature

#38 Buttons
  src/main/java/assets/css/custom.css
Labels: enhancement

#43 added unit tests to untested code that needs to be tested
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/ResultTest.java
Labels: enhancement, feature

#44 Added sonar pulse functionality.
  src/main/java/cs361/battleships/models/AtackStatus.java
  src/main/java/cs361/battleships/models/Board.java
Labels: feature

#45 Sonar
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/conf/Routes.java
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/AtackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature

#46 Captain quarters
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/AtackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Ship.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature
